fix: provide typespec docs on hover for private functions (#407)
There is a test that is failing consistently for me and I'm able to
reproduce it:

```
  1) test call hover private function (Expert.Provider.Handlers.HoverTest)
Error:      test/expert/provider/handlers/hover_test.exs:482
     match (=) failed
     code:  assert {:ok, %Structures.Hover{} = result} = hover(project, hovered)
     left:  {:ok, %GenLSP.Structures.Hover{} = result}
     right: {:ok, nil}
     stacktrace:
       test/expert/provider/handlers/hover_test.exs:495: anonymous fn/1 in Expert.Provider.Handlers.HoverTest."test call hover private function"/1
       test/expert/provider/handlers/hover_test.exs:72: anonymous fn/3 in Expert.Provider.Handlers.HoverTest.with_compiled_in/3
       test/expert/provider/handlers/hover_test.exs:91: Expert.Provider.Handlers.HoverTest.with_tmp_file/3
       test/expert/provider/handlers/hover_test.exs:494: (test)
```

Given code like this:

```elixir
defmodule MyModule do
  @spec my_fun(integer()) :: integer()
  defp my_fun(x), do: x + 1
  def my_other_fun(x, y), do: my_fun(x) + my_fun(y)
end
```

Hovering on the `my_fun/1` calls inside `my_other_fun/2` provides no
typespecs on hover.
The current code has the specs for the private functions available, but
doesn't use them. It only uses the docs for functions with doc
chunks(which makes sense at first glance) and discards the rest.
The fix in this PR is to gather the specs for functions with no docs and
produce entries for them too.